### ISSUE TITLE
Crackling noise

### ISSUE THREAD

**Issue by pol-albert** [jd-13/Carve-Distortion#10]
Hi there !
I've just installed Carve as a .so vst in Bitwig 2, linux version.
But I've got a crackling noise even if the 2 units are disabled : as soon as I start to rise the dry level, for exemple, I get those cracklings.
This noise is also present when using the distortion units BTW, but I thought it could help you to know that it's also present in the dry signal, or IMO and to be more precise, appearing on any signal outputted by the plugin.
This is not a CPU issue, the load is still very low, and it stops if i mute the sound going into the input of the plugin. 
Moreover, the crackling noise seems to be proportional to the volume of the output, if I use a LFO on the volume of the sound passing through the plugin, the cracklings also oscillate in amplitude.
Maybe you could do something ? :)

**Comment by pol-albert** [comment]
There's alwo a background "buzz" of this sound

**Comment by pol-albert** [comment]
Exemples : 
http://www6.zippyshare.com/v/rIOeU0cv/file.html - nothing passing through the dry plugin
http://www6.zippyshare.com/v/HsTqzGCM/file.html - LFO on the amplitude of a low freq sine

**Comment by jd-13** [comment]
Hi, thanks for raising this, I'll have a look over the next day or two and let you know what I find

**Comment by jd-13** [comment]
Hi, I haven't been able to reproduce the issue so far, if you could provide some of the following information that would be really helpful for my investigation:
- Linux distro/version
- Bitwig version
- Which audio engine (alsa/jack) and sample rate
- Whether the noise appears with Carve on mono or stereo tracks

Also in the first audio sample you provided I can only hear the noise on the right channel, is this how it actually sounds or was it a mono track which the website is playing on only the right channel?
